spring:
  datasource:
    url: jdbc:postgresql://aws-0-ap-southeast-1.pooler.supabase.com:5432/postgres
    username: postgres.xehsxngnbogmbgpqanal
    password: sqPXTQXvyQv4dPbw
    driver-class-name: org.postgresql.Driver
